datacarpentry/genomics-r-intro

_episodes_rmd/01-introduction.Rmd, _episodes_rmd/04-dplyr.Rmd
CRAN [asks people](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-URLs) to use this URL variant when linking to packages ;-) This PR results from a semi-automatic search-and-replace script and implements their suggestion.
=> Canonicalize CRAN links

_episodes_rmd/01-introduction.Rmd
When running this today on the AWS instance, the old search doesn't return any results.  Updated with what did work for us.
=> Possible typo on t-test

_episodes_rmd/00-introduction.Rmd, _episodes_rmd/01-r-basics.Rmd, _episodes_rmd/02-data-prelude.Rmd, _episodes_rmd/04-bioconductor-vcfr.Rmd
Forgot to update the fig path in the files after renaming.
=> Fix knitr_fig_path prefix for reordered files (part of #151)

_episodes_rmd/05-dplyr.Rmd
Currently, we filter on INDEL which is a logical column: `filter(variants, sample_id == "SRR2584863", (INDEL | QUAL >= 100))` and INDEL is logical. Instead of INDEL, we will now filter on MQ: `filter(variants, sample_id == "SRR2584863", (MQ >= 50 | QUAL >= 100))`
=> Post AUC beta run dplyr lesson updates

_episodes_rmd/04-bioconductor-vcfr.Rmd
This is a PR to address issues raised in the first beta-pilot of the lesson (outlined in #142). All of the commits address problems identified in the bioconductor lesson.
It addresses: 
- #163 
- #168 
- #169 
- #170 
- #173 
- #185 
- #186 
- #187 
- #188
=> PR to address bioconductor lesson issues from first beta

CONTRIBUTING.md
Just a quick change in CONTRIBUTING.md to match the main README's instructions to make pull requests into `main`, not `gh-pages`.
=> CONTRIBUTING.md to main branch, not gh-pages

_episodes_rmd/07-knitr-markdown.Rmd
Changed tip box at the end of the knitr episode to include code to download R package tinytex instead of having students install MiKTeX or MacTeX
=> tip-box-install-tinytex

_episodes_rmd/03-basics-factors-dataframes.Rmd
Moving this paragraph from the Bioconductor lesson to this one, per discussion with @ytakemon on #167
=> Add extra callout tip about what packages are

_episodes_rmd/05-dplyr.Rmd
This fixes the first solution block in episode 5. It was causing trouble with the transition (see https://github.com/carpentries/lesson-transition/issues/51)
=> fix malformed solution block

config.yaml
This lesson should be labelled as beta (not alpha). It is currently in beta pilots. Closes https://github.com/datacarpentry/genomics-r-intro/pull/208
=> update to beta

renv/activate.R, renv/profiles/lesson-requirements/renv.lock
I've run the package update manually because the automated workflow was having trouble after the release of {renv} 1.0.0.
This brings in updates to 30 packages. Please wait for the output to run and
then check for any new errors, warnings or surprising output changes.
```
- askpass       [1.1 -> 1.2.0]
- bslib         [repo: RSPM -> CRAN; ver: 0.5.0 -> 0.5.1]
- cpp11         [repo: RSPM -> CRAN; ver: 0.4.4 -> 0.4.6]
- curl          [repo: RSPM -> CRAN; ver: 5.0.1 -> 5.0.2]
- dbplyr        [2.3.2 -> 2.3.3]
- digest        [0.6.32 -> 0.6.33]
- dplyr         [1.1.2 -> 1.1.3]
- fontawesome   [0.5.1 -> 0.5.2]
- fs            [1.6.2 -> 1.6.3]
- gargle        [repo: RSPM -> CRAN; ver: 1.5.1 -> 1.5.2]
- ggplot2       [3.4.2 -> 3.4.3]
- gtable        [0.3.3 -> 0.3.4]
- htmltools     [repo: RSPM -> …
```
=> update 30 packages

learners/setup.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #220
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
This switches floating solution divs for the `spoiler` class introduced in the recent release of the lesson infrastructure
_If any relevant discussions have taken place elsewhere, please provide links to these._
See https://github.com/carpentries/sandpaper/pull/502#issuecomment-1698203526 for an example of a spoiler class div in action.
=> use spoiler divs for install instructions

episodes/05-dplyr.Rmd
Suspect the code above used to also use the `head` function but no longer does.  Removed the reference selecting the first 6 rows in the text description.
=> removing outdated text

episodes/06-data-visualization.Rmd
fixes #237
This change has us install and load `ggplot2` instead of the `tidyverse` which we know takes a while to install on the AWS machines in particular.  It also loads `readr` and `dplyr` for the ggplot episode.
=> Removing tidyverse install from ggplot lesson

episodes/06-data-visualization.Rmd
This consistently uses the `labs()` function's arguments instead of mixing `labs()` and `ggtitle()`
This was also changed in the r-socialsci lesson - https://github.com/datacarpentry/r-socialsci/issues/99
=> Changing ggtitle function to use labs arg

episodes/06-data-visualization.Rmd
Change all URLs to repo-local for the combined csv dataset, and fix a stray typo
=> Fix additional URLs and a typo

episodes/00-introduction.Rmd
=> Add search engine tip address #265

episodes/01-r-basics.Rmd
=> Some minor clean up (style/spacing, remove unneeded chunk, etc)

episodes/03-basics-factors-dataframes.Rmd
Revises text on base R vs add-on packages to clarify. Addresses #280
=> Revise base vs add-on package text to address #280

episodes/03-basics-factors-dataframes.Rmd
Addresses issue #285 
- Added text to explain what integers are and how they differ from numerics
Addresses issue #284 
- Breaks down code into a step-wise process to help review indexing from the previous section. 
Addresses issue #283
- Shows `str(snps)` is a character vector and that R does not intuitively know how to plot them and compares them to `str(factor_snps)`.
=> Addressing issues in mega issue section: R basics continued - factors and data frames
