- _episodes_rmd/02-r-basics.Rmd
- some minor typos/edits
- didn't any core content, yet
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a …
> Update 02-r-basics.Rmd; typos/minor edits

- _episodes_rmd/05-data-visualization.Rmd
Addresses https://github.com/datacarpentry/genomics-r-intro/issues/24 with help from @ryanpeek.
> Ggplot code to use vcf data

- _config.yml
Per @ErinBecker  This lesson is about to be released in alpha stage
> moves lesson to alpha

- _episodes_rmd/01-introduction.Rmd
thanks to @ErinBecker & @maneesha
> edit setup URL

- _episodes_rmd/04-dplyr.Rmd
Sorry for what might be a few minor PRs instead of one.  I'm working through it slowly, so I'm doing them separately.
> Fixing link to dplyr package

- _episodes_rmd/02-r-basics.Rmd
Another small grammar fix.  Series is the object and it is singular here.
> small grammar fix

- _episodes_rmd/04-dplyr.Rmd
I feel glimpse is more relevant here as opposed to head and keeps the entire code within the tidy realm
> Changed head to glimpse

- _episodes_rmd/01-introduction.Rmd
file extension ".Rproj" was missing a 'p'
> Correct typing error

- index.md
Corrected grammar error "employee" to "employ".
> Grammar Error - Index Intro

- _episodes_rmd/02-r-basics.Rmd
To the list of mathematical and functional operations on objects in R, add the operation of integer division to the list of operations that can be performed. This is often included in R introductory material to be exhaustive. It complements the modulo operator that is already invoked.
> Add integer division to list of mathematical operations

- _episodes_rmd/05-data-visualization.Rmd
Not sure if this will fix it but hoping this might fix the rendering of the last challenge.
> last challenge rendering strangely

- _episodes_rmd/04-dplyr.Rmd
Fixing long output on exercise.
> Dplyr update

- _episodes_rmd/02-r-basics.Rmd
Typo found during workshop today.  I think it might supposed to be "add" but it could in theory be "remove" too.  Feedback on which you think it should be would be great.
> Updating typo in subsetting challenge

- _episodes_rmd/03-basics-factors-dataframes.Rmd
Fixing formatting error that corrupted this exercise.
> fix formatting error in episode 3 order exercise

- .github/workflows/template.yml
- .github/workflows/website.yml
- 404.md
- CODE_OF_CONDUCT.md
- Gemfile
- Makefile
- _config.yml
- aio.md
- bin/boilerplate/CONTRIBUTING.md
- bin/boilerplate/_config.yml
- bin/dependencies.R
- bin/lesson_check.py
- bin/lesson_initialize.py
- bin/repo_check.py
- bin/reporter.py
- bin/test_lesson_check.py
- bin/util.py
- bin/workshop_check.py
there was a bug in the scripts for `make lesson-check-all` that did not handle the remote theme correctly. This was addressed in https://github.com/carpentries/styles/pull/571 
This PR brings all the latest changes in the scripts that build and check the lessons, and once merged, should address the error message seen in #108
> bring latest updates to infrastructure

- _episodes_rmd/05-dplyr.Rmd
- _episodes_rmd/06-data-visualization.Rmd
- _episodes_rmd/07-knitr-markdown.Rmd
- _episodes_rmd/08-r-help.Rmd
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
> rename and reorder episodes on dplyr ggplot knitr and help

- _episodes_rmd/05-dplyr.Rmd
Issues arising with backend read_csv conflicting with an earlier lesson which uses read.csv
> fixes issue #150 explains read_csv()

- _episodes_rmd/06-data-visualization.Rmd
Alt text contribution by Danielle Sieh for https://ggplot2.tidyverse.org/logo.png
> added alt text

- _episodes_rmd/00-introduction.Rmd
> Rephrase the first tip box to match formatting

- CONTRIBUTING.md
Update links to address issue #213
> Fix links in CONTRIBUTING per #213

- episodes/05-dplyr.Rmd
fixes broken link, Much of this lesson was copied or adapted from Jeff Hollister’s materials.
Closes #212
> Update 05-dplyr.Rmd changed broken link

- genomics-r-intro.Rproj
This adds an RStudio project file to the lesson. It is recommended to make it easier for RStudio users to contribute. This supersedes #238
> add RStudio project file

- episodes/05-dplyr.Rmd
> Adds callout on group_by behaviour

- episodes/00-introduction.Rmd
> Update 00-introduction.Rmd to fix typo

- episodes/03-basics-factors-dataframes.Rmd
> addresses why read.csv calls read.table in help doc #149

- episodes/06-data-visualization.Rmd
Closes #248 but replacing external URL to csv file to one located within this repo.
> Replace csv URL with one inside this repo per #248

- episodes/01-r-basics.Rmd
Closes #154 by adding some additional style guide examples.
> Update to include additional style guides per #154

- learners/setup.md
> Update setup with only R and Rstudio instructions

- episodes/01-r-basics.Rmd
> Add callout differentiating %in% and == to address #258

- episodes/01-r-basics.Rmd
Fixes the answer provided in "Exercise: Create objects and check their modes"
> update solution to fix issue #39

- episodes/00-introduction.Rmd
> Add more context to RStudio project viz setwd, address #144

- episodes/00-introduction.Rmd
> Remove 'mixed' to address #264

- episodes/03-basics-factors-dataframes.Rmd
Also fixed some typos and style issues in ep 3.
> Address #120 by adding short description of `$` when it is first used

- episodes/03-basics-factors-dataframes.Rmd
> Change img html tags to markdown in ep 3 per #270

- .gitignore
Small PR to add `.vscode` to `.gitignore`
> Add VS code dir to gitignore

- episodes/00-introduction.Rmd
Adding a warning in response to issue #282
> Patch for 282

- episodes/01-r-basics.Rmd
- episodes/03-basics-factors-dataframes.Rmd
> Fix markdown image syntax per issue #293

- episodes/01-r-basics.Rmd
Additional contextual help added for example
> Patch for #299

- episodes/01-r-basics.Rmd
Added additional context and explanation for golden ratio exercise.
> Add more details to golden ratio exercisesfor #298
